<!-- Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ -->
<script setup>import AdminShell from '../../components/AdminShell.vue';import StatusBadge from '../../components/StatusBadge.vue';import {products,changes,documents} from '../../api/mock';</script>
<template><AdminShell><template #title>产品驾驶舱</template>
 <div class="heading"><div><p>PRODUCT LIFECYCLE OVERVIEW</p><h1>产品驾驶舱</h1><span>统一掌握产品状态、工程变更与技术资料完整度</span></div><div><button class="btn ghost">导出简报</button><button class="btn primary">＋ 新建产品</button></div></div>
 <section class="kpis"><article><header>在管产品 <i>▱</i></header><strong>24</strong><p><b>6</b> 个产品处于研发阶段</p></article><article><header>受控物料 <i>⌘</i></header><strong>1,286</strong><p>本月新增 48 项</p></article><article class="attention"><header>进行中变更 <i>⇄</i></header><strong>18</strong><p><b>4</b> 项高风险待评审</p></article><article><header>文档发布率 <i>▤</i></header><strong>96.4%</strong><p>较上月提升 1.8%</p></article></section>
 <div class="grid two"><section class="panel lifecycle"><header><div><h2>产品生命周期分布</h2><p>当前在管产品按阶段统计</p></div><button>查看产品台账 →</button></header><div class="stage-chart"><div class="stage-count"><strong>24</strong><small>全部产品</small></div><div class="stages"><div><b style="height:32%"></b><span>概念</span><small>2</small></div><div><b style="height:47%"></b><span>设计</span><small>4</small></div><div><b style="height:64%"></b><span>试制</span><small>5</small></div><div><b style="height:88%"></b><span>量产</span><small>11</small></div><div><b style="height:32%"></b><span>退市</span><small>2</small></div></div></div></section>
 <section class="panel health"><header><div><h2>数据健康度</h2><p>产品数据规范性与完整性</p></div><em>本周</em></header><div class="health-body"><div class="ring"><b>92</b><small>/ 100</small></div><ul><li><i class="blue"></i><span>BOM 完整率</span><b>97%</b></li><li><i class="orange"></i><span>文档有效率</span><b>94%</b></li><li><i class="gray"></i><span>编码规范率</span><b>88%</b></li></ul></div></section></div>
 <div class="grid lower"><section class="panel"><header><div><h2>重点产品</h2><p>按研发进度与变更风险排序</p></div><button>全部产品 →</button></header><div class="product-list"><article v-for="p in products" :key="p.code"><div class="product-icon">{{p.model.slice(0,2)}}</div><div><b>{{p.name}}</b><small>{{p.code}} · {{p.model}} · {{p.version}}</small></div><StatusBadge :value="p.stage"/><div class="mini-progress"><span><i :style="{width:p.progress+'%'}"></i></span><small>{{p.progress}}%</small></div><em>{{p.owner}}</em></article></div></section>
 <section class="panel"><header><div><h2>待处理工程变更</h2><p>按截止时间排序</p></div><button>变更中心 →</button></header><div class="change-list"><article v-for="c in changes.slice(0,3)" :key="c.no"><div><StatusBadge :value="c.risk+'风险'"/><small>{{c.no}}</small></div><h3>{{c.title}}</h3><p>{{c.product}} · {{c.type}} · 负责人 {{c.owner}}</p><footer><span>截止 {{c.due}}</span><StatusBadge :value="c.status"/></footer></article></div></section>
 <section class="panel docs"><header><div><h2>最近更新文档</h2><p>团队技术资料动态</p></div><button>文档中心 →</button></header><div v-for="d in documents.slice(0,3)" :key="d.no" class="doc-row"><i>PDF</i><div><b>{{d.name}}</b><small>{{d.no}} · {{d.version}}</small></div><span>{{d.updated}}</span></div></section></div>
 </AdminShell></template>
