/* Copyright 2026 Shanghai Rujing Zhihua Information Technology Co., Ltd. */
package cn.zhuatech.plm.config;
import cn.zhuatech.plm.model.*; import cn.zhuatech.plm.repository.*; import org.springframework.boot.CommandLineRunner; import org.springframework.context.annotation.*; import org.springframework.security.crypto.password.PasswordEncoder; import java.time.LocalDate;
@Configuration public class DataInitializer {
    @Bean CommandLineRunner seed(UserRepository users,ProductRepository products,PartRepository parts,BomItemRepository bom,ChangeRequestRepository changes,TechnicalDocumentRepository docs,PasswordEncoder encoder){return args->{if(users.count()>0)return;
        users.save(new UserAccount("admin",encoder.encode("admin123"),"产品平台主管",UserAccount.Role.ADMIN)); users.save(new UserAccount("engineer",encoder.encode("engineer123"),"产品工程师",UserAccount.Role.PRODUCT_ENGINEER)); users.save(new UserAccount("reviewer",encoder.encode("review123"),"技术评审员",UserAccount.Role.REVIEWER));
        products.save(new Product("PRD-SV750","知华伺服驱动器","SV-750","V2.4","量产","顾远","已发布")); products.save(new Product("PRD-IO240","工业远程 IO 模块","IO-240","V1.8","量产","林澈","已发布")); products.save(new Product("PRD-GW100","边缘计算网关","GW-100","V0.9","试制","周岚","验证中")); products.save(new Product("PRD-HMI10","10.1 寸工业触控屏","HMI-101","V1.2","设计","许亦","设计中"));
        parts.save(new Part("ASM-SV750-MAIN","伺服驱动主控组件","组件","B.3","含主控板与功率板","套","已发布")); parts.save(new Part("PCB-CTRL-207","伺服主控 PCB","电子件","C.2","6 层沉金板 1.6mm","块","已发布")); parts.save(new Part("IC-MCU-1048","工业级 MCU","电子件","A.1","Cortex-M7 / 480MHz","颗","已发布")); parts.save(new Part("ENC-AL-075","铝合金散热外壳","结构件","B.1","6061-T6 阳极氧化","件","已发布")); parts.save(new Part("FAN-DC-4020","直流散热风扇","标准件","A.0","24V / 40×40×20mm","件","已发布"));
        bom.save(new BomItem("PRD-SV750",null,"ASM-SV750-MAIN",1,1.0,"套","V2.4")); bom.save(new BomItem("PRD-SV750","ASM-SV750-MAIN","PCB-CTRL-207",2,1.0,"块","V2.4")); bom.save(new BomItem("PRD-SV750","PCB-CTRL-207","IC-MCU-1048",3,1.0,"颗","V2.4")); bom.save(new BomItem("PRD-SV750",null,"ENC-AL-075",1,1.0,"件","V2.4")); bom.save(new BomItem("PRD-SV750",null,"FAN-DC-4020",1,2.0,"件","V2.4"));
        changes.save(new ChangeRequest("ECR-20260730-018","替换主控芯片并升级驱动固件","PRD-SV750","设计变更","原芯片交期延长，需完成兼容性验证","顾远",LocalDate.now().plusDays(2),"高","评审中")); changes.save(new ChangeRequest("ECN-20260729-011","散热器表面处理规范优化","PRD-SV750","工艺变更","提升盐雾环境耐久性","林澈",LocalDate.now().plusDays(5),"中","待实施")); changes.save(new ChangeRequest("ECR-20260728-006","网关电源输入范围扩展","PRD-GW100","设计变更","适配交通行业宽压供电场景","周岚",LocalDate.now().plusDays(7),"中","草稿")); changes.save(new ChangeRequest("ECN-20260724-003","IO 模块标签模板更新","PRD-IO240","文档变更","满足新版可追溯编码要求","许亦",LocalDate.now().minusDays(1),"低","验证中"));
        docs.save(new TechnicalDocument("DOC-SV750-SPEC","SV-750 产品技术规格书","产品规格","V2.4","PRD-SV750","顾远","已发布")); docs.save(new TechnicalDocument("DWG-SV750-ASM","SV-750 总装二维图","工程图纸","B.3","PRD-SV750","林澈","已发布")); docs.save(new TechnicalDocument("SOP-SV750-TEST","SV-750 出厂测试规范","测试规范","V1.7","PRD-SV750","陈静","评审中")); docs.save(new TechnicalDocument("DOC-GW100-DVT","GW-100 DVT 验证计划","验证文件","V0.6","PRD-GW100","周岚","编制中"));
    };}
}
